# Generated by Django 5.2.17 on 2026-09-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Threat Categories',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('message', 'Message'), ('url', 'URL'), ('email', 'Email')], max_length=16)),
                ('input_text', models.TextField()),
                ('input_meta', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('threat_type', models.CharField(choices=[('phishing', 'Phishing'), ('banking_scam', 'Banking scam'), ('job_scam', 'Job scam'), ('investment_scam', 'Investment scam'), ('otp_scam', 'OTP scam'), ('delivery_scam', 'Delivery scam'), ('tech_support_scam', 'Tech support scam'), ('shopping_scam', 'Shopping scam'), ('social_media_scam', 'Social media scam'), ('fake_support', 'Fake customer support'), ('suspicious_url', 'Suspicious URL'), ('none', 'No clear threat identified'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(default='completed', max_length=12)),
                ('analysis_mode', models.CharField(default='rules_only', max_length=12)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('url_analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('info', 'Info')], default='normal', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scanner.scan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('phishing', 'Phishing'), ('banking_scam', 'Banking scam'), ('job_scam', 'Job scam'), ('investment_scam', 'Investment scam'), ('otp_scam', 'OTP scam'), ('delivery_scam', 'Delivery scam'), ('tech_support_scam', 'Tech support scam'), ('shopping_scam', 'Shopping scam'), ('social_media_scam', 'Social media scam'), ('fake_support', 'Fake customer support'), ('suspicious_url', 'Suspicious URL'), ('none', 'No clear threat identified'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('key_signals', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('urgency', 'Urgency'), ('credential_request', 'Credential request'), ('financial_request', 'Financial request'), ('threat_language', 'Threat language'), ('reward_bait', 'Reward bait'), ('impersonation', 'Impersonation'), ('grammar', 'Unusual wording'), ('suspicious_url', 'Suspicious URL'), ('url_no_https', 'No HTTPS'), ('url_ip_host', 'IP address host'), ('url_lookalike', 'Lookalike domain'), ('url_shortener', 'URL shortener'), ('url_length', 'Unusual URL length'), ('url_encoded', 'Encoded characters'), ('url_subdomains', 'Excessive subdomains'), ('url_keywords', 'Risky keywords in URL'), ('sender_mismatch', 'Sender mismatch'), ('attachment', 'Attachment reference'), ('contact_pressure', 'Contact pressure'), ('excessive_caps', 'Excessive capitalization/punctuation'), ('ai_signal', 'AI-identified signal')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('evidence', models.CharField(blank=True, max_length=200)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='scanner.scan')),
            ],
            options={
                'ordering': ['-weight', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['user', '-created_at'], name='scanner_sca_user_id_5293c9_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['user', 'risk_level'], name='scanner_sca_user_id_a674f8_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['user', 'scan_type'], name='scanner_sca_user_id_e37419_idx'),
        ),
    ]
